AWSTemplateFormatVersion: 2010-09-09
Description: Creates an IAM role which trusts a GCP service account, to be called
  via AssumeRoleWithWebIdentity
Transform: AWS::Serverless-2016-10-31
Parameters:
  OIDCProviderUrl:
    Type: String
    Description: The URL of the OIDC identity provider
    AllowedPattern: ^https:\/\/.*
    ConstraintDescription: Must be a valid HTTPS URL
    Default: https://gcp.google.com/
  OIDCThumbprint:
    Type: String
    Description: A hex-encoded SHA-1 hash value of the X.509 certificate used by the
      domain where the OIDC provider makes its keys available
    AllowedPattern: ^[A-Fa-f0-9]{40}$
    ConstraintDescription: Must be a 40-character hex string
  OIDCAudiences:
    Type: CommaDelimitedList
    Description: A list of valid audience strings that the IAM OIDC provider will
      add as client IDs
Resources:
  GCPDeploymentUserRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DeploymentRole
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action: sts:AssumeRoleWithWebIdentity
          Principal:
            Federated:
              Ref: GCPIdentityProvider
          Condition:
            StringEquals:
              accounts.google.com:aud:
                Ref: OIDCAudiences
      MaxSessionDuration: 3600
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/ReadOnlyAccess
  GCPIdentityProvider:
    Type: Custom::IDP
    Properties:
      ServiceToken:
        Fn::GetAtt:
        - ProviderCreator
        - Arn
      Url:
        Ref: OIDCProviderUrl
      ThumbprintList:
      - Ref: OIDCThumbprint
      Audiences:
        Ref: OIDCAudiences
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - iam:*OpenIDConnectProvider*
            Resource: '*'
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: '*'
  ProviderCreator:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python2.7
      Handler: oidc_provider_creator.lambda_handler
      MemorySize: 128
      Timeout: 30
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Environment:
        Variables:
          AWS_ACCOUNT_ID:
            Ref: AWS::AccountId
      CodeUri: s3://cmp-stupid-inflation/575bc51a19f637015f29c5f44b2f5fd3
